checkpoint_every_n_steps:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  save_top_k: 3 # Keep only the 3 most recent checkpoints to save disk space
  monitor: "step"
  mode: "max"
  save_last: True # save model as ${save_dir}/checkpoints/last.ckpt
  dirpath: ${checkpointing.save_dir}/checkpoints
  verbose: True
  auto_insert_metric_name: False
  every_n_train_steps: 5000
